// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkipWatch.Core.Db;

#nullable disable

namespace SkipWatch.Core.Db.Migrations
{
    [DbContext(typeof(SkipWatchDbContext))]
    partial class SkipWatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SkipWatch.Core.Entities.ActivityEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RefId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_activity_recent");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCheckError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadsPlaylistId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("YoutubeChannelId")
                        .IsUnique();

                    b.HasIndex("Enabled", "LastCheckAt")
                        .HasDatabaseName("idx_channels_round_pick");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WikiStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WikiUpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.ProjectWikiJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("NextAttemptAt", "EnqueuedAt")
                        .HasDatabaseName("idx_wiki_jobs_q")
                        .HasFilter("\"Status\" = 'Queued'");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("idx_wiki_jobs_project");

                    b.ToTable("ProjectWikiJobs");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCheckError")
                        .HasColumnType("TEXT");

                    b.Property<int>("LookbackDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Enabled", "LastCheckAt")
                        .HasDatabaseName("idx_topics_round_pick");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.TopicVideo", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId", "VideoId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("idx_topic_videos_video");

                    b.ToTable("TopicVideos");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CommentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionSignal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTranscript")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LikeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Parked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ParkedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SummarizedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryMd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TranscribedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique();

                    b.HasIndex("ChannelId", "PublishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_videos_channel");

                    b.HasIndex("NextAttemptAt", "IngestedAt")
                        .HasDatabaseName("idx_videos_q_transcript")
                        .HasFilter("\"Status\" = 'Discovered' AND \"Parked\" = 0");

                    b.HasIndex("NextAttemptAt", "TranscribedAt")
                        .HasDatabaseName("idx_videos_q_summary")
                        .HasFilter("\"Status\" = 'Transcribed' AND \"Parked\" = 0");

                    b.HasIndex("Status", "PublishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_videos_status_published");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.VideoProject", b =>
                {
                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("VideoProjects");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.ProjectWikiJob", b =>
                {
                    b.HasOne("SkipWatch.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkipWatch.Core.Entities.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.TopicVideo", b =>
                {
                    b.HasOne("SkipWatch.Core.Entities.Topic", "Topic")
                        .WithMany("TopicVideos")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkipWatch.Core.Entities.Video", "Video")
                        .WithMany("TopicVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Video", b =>
                {
                    b.HasOne("SkipWatch.Core.Entities.Channel", "Channel")
                        .WithMany("Videos")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkipWatch.Core.Entities.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId");

                    b.Navigation("Channel");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.VideoProject", b =>
                {
                    b.HasOne("SkipWatch.Core.Entities.Project", "Project")
                        .WithMany("VideoProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkipWatch.Core.Entities.Video", "Video")
                        .WithMany("VideoProjects")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Channel", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Project", b =>
                {
                    b.Navigation("VideoProjects");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Topic", b =>
                {
                    b.Navigation("TopicVideos");
                });

            modelBuilder.Entity("SkipWatch.Core.Entities.Video", b =>
                {
                    b.Navigation("TopicVideos");

                    b.Navigation("VideoProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
