using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SkipWatch.Core.Services.Interfaces;
using SkipWatch.Core.Services.Utilities;
using SkipWatch.Core.Services.YouTube;

namespace SkipWatch.Core.Services.Transcripts;

/// <summary>
/// Apify <c>streamers/youtube-scraper</c>-backed transcript source. Uses the
/// <c>run-sync-get-dataset-items</c> endpoint so a single HTTP call returns the
/// scraped video object inline (no run-id polling). Per <c>prd.md</c> §3, this also
/// gives us description / duration / view-and-like counts / thumbnail in the same hit.
/// </summary>
public sealed class ApifyTranscriptSource : ITranscriptSource
{
    // run-sync-get-dataset-items runs the actor synchronously and returns dataset items inline.
    private const string ActorRunSyncEndpoint =
        "https://api.apify.com/v2/acts/streamers~youtube-scraper/run-sync-get-dataset-items";

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNameCaseInsensitive = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    private readonly HttpClient _http;
    private readonly ApifySettings _settings;
    private readonly ILogger<ApifyTranscriptSource> _logger;

    public ApifyTranscriptSource(
        HttpClient http,
        IOptions<ApifySettings> settings,
        ILogger<ApifyTranscriptSource> logger)
    {
        _http = http;
        _settings = settings.Value;
        _logger = logger;

        // Per-call timeout governs the synchronous run. Override the HttpClient default
        // (100 s) so the longer transcripts don't get truncated.
        _http.Timeout = TimeSpan.FromSeconds(_settings.RunTimeoutSeconds);
    }

    public async Task<Transcript> FetchAsync(string videoId, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(videoId))
            return Failure("Video ID is required");

        if (string.IsNullOrWhiteSpace(_settings.Token))
            return Failure("Apify token is not configured. Set Apify:Token in user-secrets.");

        var url = $"{ActorRunSyncEndpoint}?token={Uri.EscapeDataString(_settings.Token)}";
        var requestBody = new ApifyRequestBody
        {
            StartUrls = new[] { new ApifyStartUrl { Url = $"https://www.youtube.com/watch?v={videoId}" } },
            DownloadSubtitles = true,
            PreferAutoGeneratedSubtitles = _settings.PreferAutoGenerated,
            SubtitlesLanguage = _settings.PreferredLanguage
        };

        try
        {
            using var content = new StringContent(
                JsonSerializer.Serialize(requestBody, JsonOpts),
                Encoding.UTF8,
                "application/json");

            using var response = await _http.PostAsync(url, content, ct);

            if (!response.IsSuccessStatusCode)
            {
                var body = await response.Content.ReadAsStringAsync(ct);
                _logger.LogWarning("Apify returned {Status} for video {VideoId}: {Body}",
                    response.StatusCode, videoId, body);
                return Failure($"Apify {response.StatusCode}: {body}");
            }

            var stream = await response.Content.ReadAsStreamAsync(ct);
            var items = await JsonSerializer.DeserializeAsync<List<ApifyScraperItem>>(stream, JsonOpts, ct);

            var item = items?.FirstOrDefault();
            if (item is null)
                return Failure("Apify returned an empty dataset");

            var subtitle = SelectBestSubtitle(item.Subtitles);
            var transcriptText = subtitle is null
                ? null
                : SrtConverter.ConvertSrtToPrdFormat(subtitle.Srt ?? string.Empty);

            return new Transcript(
                Success: true,
                TranscriptText: string.IsNullOrWhiteSpace(transcriptText) ? null : transcriptText,
                TranscriptLang: subtitle?.Language,
                HasTranscript: !string.IsNullOrWhiteSpace(transcriptText),
                Description: item.Text,
                DurationSeconds: DurationParser.ParseToSeconds(item.Duration) is var d and > 0 ? d : null,
                ViewCount: item.ViewCount,
                LikeCount: item.Likes,
                CommentsCount: item.CommentsCount,
                ThumbnailUrl: item.ThumbnailUrl,
                ErrorMessage: null);
        }
        catch (TaskCanceledException tcex) when (!ct.IsCancellationRequested)
        {
            _logger.LogError(tcex, "Apify call timed out for video {VideoId}", videoId);
            return Failure($"Apify call timed out after {_settings.RunTimeoutSeconds}s");
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            _logger.LogError(ex, "Unexpected error fetching transcript for video {VideoId}", videoId);
            return Failure(ex.Message);
        }
    }

    private static ApifySubtitle? SelectBestSubtitle(List<ApifySubtitle>? subtitles)
    {
        if (subtitles is null || subtitles.Count == 0)
            return null;

        // Prefer a manual English caption, then any English, then anything that has SRT content.
        return subtitles.FirstOrDefault(s =>
                   string.Equals(s.Language, "en", StringComparison.OrdinalIgnoreCase)
                   && !string.Equals(s.Type, "auto_generated", StringComparison.OrdinalIgnoreCase)
                   && !string.IsNullOrWhiteSpace(s.Srt))
               ?? subtitles.FirstOrDefault(s =>
                   string.Equals(s.Language, "en", StringComparison.OrdinalIgnoreCase)
                   && !string.IsNullOrWhiteSpace(s.Srt))
               ?? subtitles.FirstOrDefault(s => !string.IsNullOrWhiteSpace(s.Srt));
    }

    private static Transcript Failure(string message) =>
        new(false, null, null, false, null, null, null, null, null, null, message);

    // -- Apify request/response DTOs (mirror only the fields we use) ---------------------------

    private sealed class ApifyRequestBody
    {
        [JsonPropertyName("startUrls")] public ApifyStartUrl[] StartUrls { get; set; } = Array.Empty<ApifyStartUrl>();
        [JsonPropertyName("downloadSubtitles")] public bool DownloadSubtitles { get; set; }
        [JsonPropertyName("preferAutoGeneratedSubtitles")] public bool PreferAutoGeneratedSubtitles { get; set; }
        [JsonPropertyName("subtitlesLanguage")] public string SubtitlesLanguage { get; set; } = "en";
    }

    private sealed class ApifyStartUrl
    {
        [JsonPropertyName("url")] public string Url { get; set; } = string.Empty;
    }

    private sealed class ApifyScraperItem
    {
        [JsonPropertyName("text")] public string? Text { get; set; }
        [JsonPropertyName("duration")] public string? Duration { get; set; }
        [JsonPropertyName("viewCount")] public long? ViewCount { get; set; }
        [JsonPropertyName("likes")] public long? Likes { get; set; }
        [JsonPropertyName("commentsCount")] public long? CommentsCount { get; set; }
        [JsonPropertyName("thumbnailUrl")] public string? ThumbnailUrl { get; set; }
        [JsonPropertyName("subtitles")] public List<ApifySubtitle>? Subtitles { get; set; }
    }

    private sealed class ApifySubtitle
    {
        [JsonPropertyName("language")] public string? Language { get; set; }
        [JsonPropertyName("type")] public string? Type { get; set; }
        [JsonPropertyName("srt")] public string? Srt { get; set; }
    }
}
