namespace SkipWatch.Core.Services.Transcripts;

public class ApifySettings
{
    /// <summary>
    /// Apify API token. Stored in user-secrets during development
    /// (<c>dotnet user-secrets set "Apify:Token" "..."</c>); env var on the shipped binary.
    /// </summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// Per-video timeout for the run-sync call. Apify's actor typically returns in 8–30 s
    /// but a long video with auto-caption fallback can take longer. Default 5 minutes.
    /// </summary>
    public int RunTimeoutSeconds { get; set; } = 300;

    /// <summary>
    /// Preferred subtitle language. Falls back to whatever the actor returns if absent.
    /// </summary>
    public string PreferredLanguage { get; set; } = "en";

    /// <summary>
    /// When true, accept auto-generated captions if no manual ones exist.
    /// Disable to force the actor's Whisper fallback path (more expensive, but cleaner output).
    /// </summary>
    public bool PreferAutoGenerated { get; set; } = true;
}
